### ISSUE TITLE
Integrate a test suite

### ISSUE THREAD

**Issue by tomschr** [SchleichsSalaticus/reportdaily#9]
# Situation

As the script complexity will raise over time, we need a test suite.

# Proposed Solution

Use the [pytest](https://pytest.org) framework.

**Subtasks**

* [x] Create a `tests` directory. This will contain your complete test suite.
* [x] Create a `devel-requirements.txt` file which contains the pytest dependency.
* [x] Set some pytest options in a config file (`setup.cfg`, `pytest.ini` etc.)
* [x] Write your test and add comments (`given`, `when`and `then`, see below).
* [x] Apply the "Give-when-then" or "Arrange-Act-Assert" methodology for each test (both are basically the same)
* [x] Create a `tests/test_cli.py` to test the `--version` and `--help` options.

# Further Information
* [Toms' pytest cheatsheet](https://gitlab.com/tomschr/python-cheatsheets/uploads/18ede47408b38af7a1af8471af70232e/pytest-cheatsheet.pdf)
* [Writing test cases with given, when and then](https://stribny.name/blog/2018/11/writing-test-cases-with-given-when-and-then/)
* [Arrange-Act-Assert: A Pattern for Writing Good Tests](https://automationpanda.com/2020/07/07/arrange-act-assert-a-pattern-for-writing-good-tests/)
